apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
status: {}
