apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  selector:
    app: wireguard
  ports:
    - name: "51820"
      port: 51820
      protocol: UDP
      targetPort: 51820
      nodePort: 30001
  type: NodePort
status:
  loadBalancer: {}